version: 2

jobs:
  build:
    docker:
      - image: dramforever/os-lectures-build
    steps:
      - checkout
      - run:
          name: Update repo.json
          command: |
            /root/.nix-profile/bin/nix run nixpkgs.nix-prefetch-git -c \
              nix-prefetch-git --url "https://github.com/LearningOS/os-lectures.git" > repo.json

      - run:
          name: Build
          command: |
            /root/.nix-profile/bin/nix-build

      - run:
          name: Copy artifacts
          command: cp -rH result output

      - store_artifacts:
          path: output
          desination: /
