version: 2

jobs:
  build:
    docker:
      - image: ubuntu:eoan
    steps:
      - checkout

      - run:
          name: Install
          command: |
            apt update
            apt install -y git fonts-noto-cjk  fonts-noto-cjk-extra fonts-noto-mono texlive-full

      - run:
          name: Build
          command: |
            mkdir result
            git clone --depth=1 https://github.com/LearningOS/os-lectures.git
            cd os-lectures

            for lec in lecture*; do
              make -f ../Makefile -C "$lec" all
              cp "$lec/$lec".pdf ../result/
              cp "$lec"/*.log ../result/logs
            done

      - store_artifacts:
          path: result
          desination: /
