version: 2

jobs:
  build:
    docker:
      - image: dramforever/os-lectures-build
    steps:
      - checkout
      - run:
          name: Update repo.json
          command: |
            /root/.nix-profile/bin/nix run nixpkgs.nix-prefetch-git -c \
              nix-prefetch-git --url "https://github.com/LearningOS/os-lectures.git" > repo.json

      - run:
          name: Build
          command: |
            /root/.nix-profile/bin/nix-build

      - run:
          name: Copy artifacts
          command: cp -rH result output

      - run:
          name: Release
          command: |
            apk add hub

            files=""

            for i in output/*.pdf; do
              files="$files -a $i"
            done

            cat > release.txt <<END
            Build $(TZ=Asia/Shanghai date +"%Y-%m-%d")
            [Build log]($CIRCLE_BUILD_URL)
            END

            hub release create $files -F release.txt "v$CIRCLE_BUILD_NUM"

      - store_artifacts:
          path: output
          desination: /
